INSERT INTO `regioni` (`titolo`, tipo, nazione, id_nazione, alias, id_order) VALUES
('Abruzzo','SYS','IT', 2, 'abruzzo', 1),
('Basilicata','SYS','IT', 2, 'basilicata', 2),
('Calabria','SYS','IT', 2, 'calabria', 3),
('Campania','SYS','IT', 2, 'campania', 4),
('Emilia-Romagna','SYS','IT', 2, 'emilia-romagna', 5),
('Friuli-Venezia Giulia','SYS','IT', 2, 'friuli-venezia-giulia', 6),
('Lazio','SYS','IT', 2, 'lazio', 7),
('Liguria','SYS','IT', 2, 'liguria', 8),
('Lombardia','SYS','IT', 2, 'lombardia', 9),
('Marche','SYS','IT', 2, 'marche', 10),
('Molise','SYS','IT', 2, 'molise', 11),
('Piemonte','SYS','IT', 2, 'piemonte', 12),
('Puglia','SYS','IT', 2, 'puglia', 13),
('Sardegna','SYS','IT', 2, 'sardegna', 14),
('Sicilia','SYS','IT', 2, 'sicilia', 15),
('Toscana','SYS','IT', 2, 'toscana', 16),
('Trentino-Alto Adige/Südtirol','SYS','IT', 2, 'trentino-alto-adige-sudtirol', 17),
('Umbria','SYS','IT', 2, 'umbria', 18),
('Valle d\'Aosta/Vallée d\'Aoste','SYS','IT', 2, 'valle-d-aosta', 19),
('Veneto','SYS','IT', 2, 'veneto', 20);
