INSERT INTO `cookie_archivio` (`id_cookie_archivio`, `data_creazione`, `titolo`, `dominio`, `path`, `durata`, `servizio`, `secure`, `same_site`, `cross_site`, `note`) VALUES
(1, '2024-11-22 12:36:07', 'AEC', '.google.com', '/', '', 'YouTube', '✓', 'Lax', '', ''),
(6, '2024-11-22 12:36:07', 'LOGIN_INFO', '.youtube.com', '/', '', 'YouTube', '✓', 'None', '', ''),
(8, '2024-11-22 12:36:07', 'OSID', 'play.google.com', '/', '', 'YouTube', '✓', '', '', 'Cookie pubblicitario di Google'),
(9, '2024-11-22 12:36:07', 'PREF', '.youtube.com', '/', '', 'YouTube', '✓', '', '', ''),
(19, '2024-11-22 12:36:07', 'VISITOR_INFO1_LIVE', '.youtube.com', '/', '', 'YouTube', '✓', 'None', '✓', 'Per fornire la pubblicazione di annunci o il retargeting, archiviare e tracciare l\'identità di un visitatore, archiviare e monitorare l\'interazione.'),
(20, '2024-11-22 12:36:07', 'VISITOR_PRIVACY_METADATA', '.youtube.com', '/', '', 'YouTube', '✓', 'None', '✓', 'Utilizzato per tracciare e arricchire le impostazioni sulla privacy degli utenti sulla piattaforma Youtube'),
(38, '2024-11-22 12:36:07', '__Secure-OSID', 'play.google.com', '/', '', 'YouTube', '✓', 'None', '', ''),
(41, '2024-11-22 12:36:07', '_gcl_au', '.play.google.com', '/', '', 'Google Adsense', '', '', '', 'Per archiviare e monitorare le conversioni.'),
(42, '2024-11-22 12:36:07', 'AEC', '.google.com', '/', '', 'Google', '✓', 'Lax', '', 'I cookie “AEC” garantiscono che le richieste all’interno di una sessione di navigazione vengano effettuate dall’utente e non da altri siti. Questi cookie impediscono ai siti dannosi di agire per conto di un utente a sua insaputa'),
(43, '2024-11-22 12:36:07', 'APISID', '.google.com', '/', '', 'Google Ads', '', '', '', 'Funzionalità sconosciuta'),
(44, '2024-11-22 12:36:07', 'HSID', '.google.com', '/', '', 'Google Ads', '', '', '', 'Per fornire prevenzione delle frodi.'),
(45, '2024-11-22 12:36:07', 'NID', '.google.com', '/', '', 'Google Ads', '✓', 'None', '', 'Per fornire la pubblicazione di annunci o il retargeting, memorizzare le preferenze dell\'utente.'),
(47, '2024-11-22 12:36:07', 'SEARCH_SAMESITE', '.google.com', '/', '', 'GoogleMapsScript', '', 'Strict', '', 'Questo cookie viene utilizzato per impedire al browser di inviare questo cookie insieme alle richieste tra siti.'),
(48, '2024-11-22 12:36:07', 'SID', '.google.com', '/', '', 'GoogleMapsScript', '', '', '', 'Per fornire la pubblicazione di annunci o il retargeting, fornire prevenzione delle frodi.'),
(49, '2024-11-22 12:36:07', 'SIDCC', '.google.com', '/', '', 'GoogleMapsScript', '', '', '', 'Per fornire l\'identificazione del traffico web affidabile.'),
(50, '2024-11-22 12:36:07', 'SSID', '.google.com', '/', '', 'Google Ads', '✓', '', '', 'Funzionalità sconosciuta'),
(51, '2024-11-22 12:36:07', '__Secure-1PAPISID', '.google.com', '/', '', 'GoogleMapsScript', '✓', '', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(52, '2024-11-22 12:36:07', '__Secure-1PSID', '.google.com', '/', '', 'GoogleMapsScript', '✓', '', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(53, '2024-11-22 12:36:07', '__Secure-1PSIDCC', '.google.com', '/', '', 'GoogleMapsScript', '✓', '', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(54, '2024-11-22 12:36:07', '__Secure-1PSIDTS', '.google.com', '/', '', 'GoogleMapsScript', '✓', '', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(55, '2024-11-22 12:36:07', '__Secure-3PAPISID', '.google.com', '/', '', 'GoogleMapsScript', '✓', 'None', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(56, '2024-11-22 12:36:07', '__Secure-3PSID', '.google.com', '/', '', 'GoogleMapsScript', '✓', 'None', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(57, '2024-11-22 12:36:07', '__Secure-3PSIDCC', '.google.com', '/', '', 'GoogleMapsScript', '✓', 'None', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(58, '2024-11-22 12:36:07', '__Secure-3PSIDTS', '.google.com', '/', '', 'GoogleMapsScript', '✓', 'None', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(59, '2024-11-22 12:36:07', '__Secure-ENID', '.google.com', '/', '', 'GoogleMapsScript', '✓', 'Lax', '', 'Utilizzato da Google per memorizzare informazioni sull\'utilizzo dei suoi servizi da parte dell\'utente.'),
(60, '2024-11-24 12:33:30', '_ga', '.lachiocciolababy.it', '/', '', 'GoogleAnalytics', '', '', '', 'Per archiviare e contare le visualizzazioni di pagina.'),
(61, '2024-11-24 12:33:30', '_ga_*', '.lachiocciolababy.it', '/', '', 'GoogleAnalytics', '', '', '', 'Per archiviare e contare le visualizzazioni di pagina.'),
(62, '2024-11-24 12:33:30', '_gat_gtag_UA_*', '.lachiocciolababy.it', '/', '', 'GoogleAnalytics', '', '', '', 'Per memorizzare un ID utente univoco.'),
(63, '2024-11-24 12:33:30', '_gcl_au', '.lachiocciolababy.it', '/', '', 'Google Adsense', '', '', '', 'Per archiviare e monitorare le conversioni.'),
(64, '2024-11-24 12:33:30', '_gid', '.lachiocciolababy.it', '/', '', 'GoogleAnalytics', '', '', '', 'Per archiviare e contare le visualizzazioni di pagina.'),
(65, '2024-11-24 12:33:30', '_fbp', '.lachiocciolababy.it', '/', '', 'Facebook', '', 'Lax', '', 'Per archiviare e monitorare le visite sui siti Web.');