CREATE TABLE `ordini_acquisto` (
  `id_ordine_acquisto` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `data_creazione` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_fornitore` INT UNSIGNED not null default 0,
  `ragione_sociale` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `p_iva` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  codice_fiscale varchar(255) not null default '',
  `telefono` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `telefono_2` varchar(100) NOT NULL DEFAULT '',
  `referente` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `email` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `email_amministrativa` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `pec` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  `indirizzo` varchar(80) NOT NULL DEFAULT '',
  `numero_civico` char(10) NOT NULL DEFAULT '',
  `nazione` char(2) NOT NULL DEFAULT 'IT',
  `provincia` varchar(100) NOT NULL DEFAULT '',
  `comune` varchar(80) NOT NULL DEFAULT '',
  `cap` varchar(10) NOT NULL DEFAULT '',
  `localita` varchar(200) NOT NULL DEFAULT '',
  telefono_referente varchar(255) not null default '',
  cellulare_referente varchar(255) not null default '',
  `email_referente` VARCHAR(255) NOT NULL DEFAULT '',
   data_ordine date null default null,
   `numero_ordine` INT UNSIGNED not null default 0,
  `id_order` int UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB;