<?php

// EcommerceMyAdmin is a PHP CMS based on MvcMyLibrary
//
// Copyright (C) 2009 - 2025  Antonio Gallo (info@laboratoriolibero.com)
// See COPYRIGHT.txt and LICENSE.txt.
//
// This file is part of EcommerceMyAdmin
//
// EcommerceMyAdmin is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// EcommerceMyAdmin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with EcommerceMyAdmin.  If not, see <http://www.gnu.org/licenses/>.

if (!defined('EG')) die('Direct access not allowed!');

// function inspirated by reply found here: https://stackoverflow.com/questions/34231938/detect-bot-using-php
class Device
{
	private static $botsSorted = false;
	
	public static $bots = array(
		'Googlebot'
		, 'Baiduspider'
		, 'ia_archiver'
		, 'R6_FeedFetcher'
		, 'NetcraftSurveyAgent'
		, 'Sogou web spider'
		, 'bingbot'
		, 'Yahoo! Slurp'
		, 'facebookexternalhit'
		, 'PrintfulBot'
		, 'msnbot'
		, 'Twitterbot'
		, 'UnwindFetchor'
		, 'urlresolver'
		, 'Butterfly'
		, 'TweetmemeBot'
		, 'PaperLiBot'
		, 'MJ12bot'
		, 'AhrefsBot'
		, 'Exabot'
		, 'Ezooms'
		, 'YandexBot'
		, 'SearchmetricsBot'
		, 'picsearch'
		, 'TweetedTimes Bot'
		, 'QuerySeekerSpider'
		, 'ShowyouBot'
		, 'woriobot'
		, 'merlinkbot'
		, 'BazQuxBot'
		, 'Kraken'
		, 'SISTRIX Crawler'
		, 'R6_CommentReader'
		, 'magpie-crawler'
		, 'GrapeshotCrawler'
		, 'PercolateCrawler'
		, 'MaxPointCrawler'
		, 'NetSeer crawler'
		, 'grokkit-crawler'
		, 'SMXCrawler'
		, 'PulseCrawler'
		, 'Y!J-BRW'
		, '80legs'
		, 'Mediapartners-Google'
		, 'InAGist'
		, 'Python-urllib'
		, 'NING'
		, 'TencentTraveler'
		, 'Feedfetcher-Google'
		, 'mon.itor.us'
		, 'spbot'
		, 'Feedly'
		, 'bitlybot'
		, 'ADmantX'
		, 'Niki-Bot'
		, 'Pinterest'
		, 'python-requests'
		, 'DotBot'
		, 'HTTP_Request2'
		, 'linkdexbot'
		, 'A6-Indexer'
		, 'TwitterFeed'
		, 'Microsoft Office'
		, 'Pingdom'
		, 'BTWebClient'
		, 'KatBot'
		, 'SiteCheck'
		, 'proximic'
		, 'Sleuth'
		, 'Abonti'
		, '(BOT for JCE)'
		, 'Tiny Tiny RSS'
		, 'newsblur'
		, 'updown_tester'
		, 'linkdex'
		, 'baidu'
		, 'searchmetrics'
		, 'genieo'
		, 'majestic12'
		, 'spinn3r'
		, 'profound'
		, 'domainappender'
		, 'VegeBot'
		, 'terrykyleseoagency.com'
		, 'CommonCrawler Node'
		, 'AdlesseBot'
		, 'libwww-perl'
		, 'rogerbot-crawler'
		, 'ltx71'
		, 'Qwantify'
		, 'Traackr.com'
		, 'Re-Animator Bot'
		, 'Pcore-HTTP'
		, 'BoardReader'
		, 'omgili'
		, 'okhttp'
		, 'CCBot'
		, 'Java/1.8'
		, 'semrush.com'
		, 'feedbot'
		, 'CommonCrawler'
		, 'ibwww-perl'
		, 'rogerbot'
		, 'MegaIndex'
		, 'BLEXBot'
		, 'FlipboardProxy'
		, 'techinfo@ubermetrics-technologies.com'
		, 'trendictionbot'
		, 'Mediatoolkitbot'
		, 'trendiction'
		, 'ubermetrics'
		, 'ScooperBot'
		, 'TrendsmapResolver'
		, 'Nuzzel'
		, 'Go-http-client'
		, 'Applebot'
		, 'LivelapBot'
		, 'GroupHigh'
		, 'SemrushBot'
		, 'commoncrawl'
		, 'istellabot'
		, 'DomainCrawler'
		, 'cs.daum.net'
		, 'StormCrawler'
		, 'GarlikCrawler'
		, 'The Knowledge AI'
		, 'getstream.io/winds'
		, 'YisouSpider'
		, 'archive.org_bot'
		, 'semantic-visions.com'
		, 'FemtosearchBot'
		, '360Spider'
		, 'linkfluence.com'
		, 'glutenfreepleasure.com'
		, 'Gluten Free Crawler'
		, 'YaK/1.0'
		, 'Cliqzbot'
		, 'app.hypefactors.com'
		, 'axios'
		, 'webdatastats.com'
		, 'schmorp.de'
		, 'SEOkicks'
		, 'DuckDuckBot'
		, 'Barkrowler'
		, 'ZoominfoBot'
		, 'Linguee Bot'
		, 'Mail.RU_Bot'
		, 'OnalyticaBot'
		, 'admantx-adform'
		, 'Zombiebot'
		, 'Nutch'
		, 'SemanticScholarBot'
		, 'Jetslide'
		, 'scalaj-http'
		, 'XoviBot'
		, 'sysomos.com'
		, 'PocketParser'
		, 'newspaper'
		, 'serpstatbot'
		, 'MetaJobBot'
		, 'SeznamBot/3.2'
		, 'VelenPublicWebCrawler/1.0'
		, 'WordPress.com mShots'
		, 'adscanner'
		, 'BacklinkCrawler'
		, 'netEstate NE Crawler'
		, 'Astute SRM'
		, 'GigablastOpenSource/1.0'
		, 'DomainStatsBot'
		, 'Winds: Open Source RSS & Podcast'
		, 'dlvr.it'
		, 'BehloolBot'
		, '7Siters'
		, 'AwarioSmartBot'
		, 'Apache-HttpClient/5'
		, 'Seekport Crawler'
		, 'AHC/2.1'
		, 'eCairn-Grabber'
		, 'mediawords bot'
		, 'PHP-Curl-Class'
		, 'Scrapy'
		, 'curl/7'
		, 'Blackboard'
		, 'NetNewsWire'
		, 'node-fetch'
		, 'admantx'
		, 'metadataparser'
		, 'Domains Project'
		, 'SerendeputyBot'
		, 'Moreover'
		, 'DuckDuckGo' 
		, 'monitoring-plugins'
		, 'Selfoss'
		, 'acebookexternalhit'
		, 'SpiderLing'
		, 'Cocolyzebot'
		, 'TTD-Content'
		, 'superfeedr'
		, 'Twingly'
		, 'Google-Apps-Scrip'
		, 'LinkpadBot'
		, 'CensysInspect'
		, 'Reeder'
		, 'tweetedtimes'
		, 'Amazonbot'
		, 'MauiBot'
		, 'Symfony BrowserKit'
		, 'DataForSeoBot'
		, 'GoogleProducer'
		, 'TinEye-bot-live'
		, 'sindresorhus/got'
		, 'CriteoBot'
		, 'Down/5'
		, 'Yahoo Ad monitoring'
		, 'MetaInspector'
		, 'PetalBot'
		, 'MetadataScraper'
		, 'Cloudflare SpeedTest'
		, 'aiohttp'
		, 'AppEngine-Google'
		, 'heritrix'
		, 'sqlmap'
		, 'Buck'
		, 'wp_is_mobile'
		, '01h4x.com'
		, '404checker'
		, '404enemy'
		, 'AIBOT'
		, 'ALittle Client'
		, 'ASPSeek'
		, 'Aboundex'
		, 'Acunetix'
		, 'AfD-Verbotsverfahren'
		, 'AiHitBot'
		, 'Aipbot'
		, 'Alexibot'
		, 'AllSubmitter'
		, 'Alligator'
		, 'AlphaBot'
		, 'Anarchie'
		, 'Anarchy'
		, 'Anarchy99'
		, 'Ankit'
		, 'Anthill'
		, 'Apexoo'
		, 'Aspiegel'
		, 'Asterias'
		, 'Atomseobot'
		, 'Attach'
		, 'AwarioRssBot'
		, 'BBBike'
		, 'BDCbot'
		, 'BDFetch'
		, 'BackDoorBot'
		, 'BackStreet'
		, 'BackWeb'
		, 'Backlink-Ceck'
		, 'Badass'
		, 'Bandit'
		, 'BatchFTP'
		, 'Battleztar Bazinga'
		, 'BetaBot'
		, 'Bigfoot'
		, 'Bitacle'
		, 'BlackWidow'
		, 'Black Hole'
		, 'Blow'
		, 'BlowFish'
		, 'Boardreader'
		, 'Bolt'
		, 'BotALot'
		, 'Brandprotect'
		, 'Brandwatch'
		, 'Buddy'
		, 'BuiltBotTough'
		, 'BuiltWith'
		, 'Bullseye'
		, 'BunnySlippers'
		, 'BuzzSumo'
		, 'CATExplorador'
		, 'CODE87'
		, 'CSHttp'
		, 'Calculon'
		, 'CazoodleBot'
		, 'Cegbfeieh'
		, 'CheTeam'
		, 'CheeseBot'
		, 'CherryPicker'
		, 'ChinaClaw'
		, 'Chlooe'
		, 'Citoid'
		, 'Claritybot'
		, 'Cloud mapping'
		, 'Cogentbot'
		, 'Collector'
		, 'Copier'
		, 'CopyRightCheck'
		, 'Copyscape'
		, 'Cosmos'
		, 'Craftbot'
		, 'Crawling at Home Project'
		, 'CrazyWebCrawler'
		, 'Crescent'
		, 'CrunchBot'
		, 'Curious'
		, 'Custo'
		, 'CyotekWebCopy'
		, 'DBLBot'
		, 'DIIbot'
		, 'DSearch'
		, 'DTS Agent'
		, 'DataCha0s'
		, 'DatabaseDriverMysqli'
		, 'Demon'
		, 'Deusu'
		, 'Devil'
		, 'Digincore'
		, 'DigitalPebble'
		, 'Dirbuster'
		, 'Disco'
		, 'Discobot'
		, 'Discoverybot'
		, 'Dispatch'
		, 'DittoSpyder'
		, 'DnBCrawler-Analytics'
		, 'DnyzBot'
		, 'DomCopBot'
		, 'DomainAppender'
		, 'DomainSigmaCrawler'
		, 'Dotbot'
		, 'Download Wonder'
		, 'Dragonfly'
		, 'Drip'
		, 'ECCP/1.0'
		, 'EMail Siphon'
		, 'EMail Wolf'
		, 'EasyDL'
		, 'Ebingbong'
		, 'Ecxi'
		, 'EirGrabber'
		, 'EroCrawler'
		, 'Evil'
		, 'Express WebPictures'
		, 'ExtLinksBot'
		, 'Extractor'
		, 'ExtractorPro'
		, 'Extreme Picture Finder'
		, 'EyeNetIE'
		, 'FDM'
		, 'FHscan'
		, 'Fimap'
		, 'Firefox/7.0'
		, 'FlashGet'
		, 'Flunky'
		, 'Foobot'
		, 'Freeuploader'
		, 'FrontPage'
		, 'Fuzz'
		, 'FyberSpider'
		, 'Fyrebot'
		, 'G-i-g-a-b-o-t'
		, 'GT::WWW'
		, 'GalaxyBot'
		, 'Genieo'
		, 'GermCrawler'
		, 'GetRight'
		, 'GetWeb'
		, 'Getintent'
		, 'Gigabot'
		, 'Go!Zilla'
		, 'Go-Ahead-Got-It'
		, 'GoZilla'
		, 'Gotit'
		, 'GrabNet'
		, 'Grabber'
		, 'Grafula'
		, 'GrapeFX'
		, 'GridBot'
		, 'HEADMasterSEO'
		, 'HMView'
		, 'HTMLparser'
		, 'HTTP::Lite'
		, 'HTTrack'
		, 'Haansoft'
		, 'HaosouSpider'
		, 'Harvest'
		, 'Havij'
		, 'Hloader'
		, 'HonoluluBot'
		, 'Humanlinks'
		, 'HybridBot'
		, 'IDBTE4M'
		, 'IDBot'
		, 'IRLbot'
		, 'Iblog'
		, 'Id-search'
		, 'IlseBot'
		, 'Image Fetch'
		, 'Image Sucker'
		, 'IndeedBot'
		, 'Indy Library'
		, 'InfoNaviRobot'
		, 'InfoTekies'
		, 'Intelliseek'
		, 'InterGET'
		, 'InternetSeer'
		, 'Internet Ninja'
		, 'Iria'
		, 'Iskanie'
		, 'IstellaBot'
		, 'JOC Web Spider'
		, 'JamesBOT'
		, 'Jbrofuzz'
		, 'JennyBot'
		, 'JetCar'
		, 'Jetty'
		, 'JikeSpider'
		, 'Joomla'
		, 'Jorgee'
		, 'JustView'
		, 'Jyxobot'
		, 'Kenjin Spider'
		, 'Keybot Translation-Search-Machine'
		, 'Keyword Density'
		, 'Kinza'
		, 'Kozmosbot'
		, 'LNSpiderguy'
		, 'LWP::Simple'
		, 'Lanshanbot'
		, 'Larbin'
		, 'Leap'
		, 'LeechFTP'
		, 'LeechGet'
		, 'LexiBot'
		, 'Lftp'
		, 'LibWeb'
		, 'Libwhisker'
		, 'LieBaoFast'
		, 'Lightspeedsystems'
		, 'Likse'
		, 'LinkScan'
		, 'LinkWalker'
		, 'Linkbot'
		, 'LinkextractorPro'
		, 'LinksManager'
		, 'LinqiaMetadataDownloaderBot'
		, 'LinqiaRSSBot'
		, 'LinqiaScrapeBot'
		, 'Lipperhey'
		, 'Lipperhey Spider'
		, 'Litemage_walker'
		, 'Lmspider'
		, 'MFC_Tear_Sample'
		, 'MIDown tool'
		, 'MIIxpc'
		, 'MQQBrowser'
		, 'MSFrontPage'
		, 'MSIECrawler'
		, 'MTRobot'
		, 'Mag-Net'
		, 'Magnet'
		, 'Majestic-SEO'
		, 'Majestic12'
		, 'Majestic SEO'
		, 'MarkMonitor'
		, 'MarkWatch'
		, 'Mass Downloader'
		, 'Masscan'
		, 'Mata Hari'
		, 'Mb2345Browser'
		, 'MeanPath Bot'
		, 'Meanpathbot'
		, 'metauri'
		, 'MicroMessenger'
		, 'Microsoft Data Access'
		, 'Microsoft URL Control'
		, 'Minefield'
		, 'Mister PiX'
		, 'Moblie Safari'
		, 'Mojeek'
		, 'Mojolicious'
		, 'MolokaiBot'
		, 'Morfeus Fucking Scanner'
		, 'Mozlila'
		, 'Mr.4x3'
		, 'Msrabot'
		, 'Musobot'
		, 'NICErsPRO'
		, 'NPbot'
		, 'Name Intelligence'
		, 'Nameprotect'
		, 'Navroad'
		, 'NearSite'
		, 'Needle'
		, 'Nessus'
		, 'NetAnts'
		, 'NetLyzer'
		, 'NetMechanic'
		, 'NetSpider'
		, 'NetZIP'
		, 'Net Vampire'
		, 'Netcraft'
		, 'Nettrack'
		, 'Netvibes'
		, 'NextGenSearchBot'
		, 'Nibbler'
		, 'Niki-bot'
		, 'Nikto'
		, 'NimbleCrawler'
		, 'Nimbostratus'
		, 'Ninja'
		, 'Nmap'
		, 'Nuclei'
		, 'Octopus'
		, 'Offline Explorer'
		, 'Offline Navigator'
		, 'OnCrawl'
		, 'OpenLinkProfiler'
		, 'OpenVAS'
		, 'Openfind'
		, 'Openvas'
		, 'OrangeBot'
		, 'OrangeSpider'
		, 'OutclicksBot'
		, 'OutfoxBot'
		, 'PECL::HTTP'
		, 'PHPCrawl'
		, 'POE-Component-Client-HTTP'
		, 'PageAnalyzer'
		, 'PageGrabber'
		, 'PageScorer'
		, 'PageThing.com'
		, 'Page Analyzer'
		, 'Pandalytics'
		, 'Panscient'
		, 'Papa Foto'
		, 'Pavuk'
		, 'PeoplePal'
		, 'Petalbot'
		, 'Pi-Monster'
		, 'Picscout'
		, 'Picsearch'
		, 'PictureFinder'
		, 'Piepmatz'
		, 'Pimonster'
		, 'Pixray'
		, 'PleaseCrawl'
		, 'Pockey'
		, 'ProPowerBot'
		, 'ProWebWalker'
		, 'Probethenet'
		, 'Psbot'
		, 'Pu_iN'
		, 'Pump'
		, 'PxBroker'
		, 'PyCurl'
		, 'QueryN Metasearch'
		, 'Quick-Crawler'
		, 'RSSingBot'
		, 'RankActive'
		, 'RankActiveLinkBot'
		, 'RankFlex'
		, 'RankingBot'
		, 'RankingBot2'
		, 'Rankivabot'
		, 'RankurBot'
		, 'Re-re'
		, 'ReGet'
		, 'RealDownload'
		, 'Reaper'
		, 'RebelMouse'
		, 'Recorder'
		, 'RedesScrapy'
		, 'RepoMonkey'
		, 'Ripper'
		, 'RocketCrawler'
		, 'Rogerbot'
		, 'SBIder'
		, 'SEOlyticsCrawler'
		, 'SEOprofiler'
		, 'SEOstats'
		, 'SISTRIX'
		, 'SMTBot'
		, 'SalesIntelligent'
		, 'ScanAlert'
		, 'Scanbot'
		, 'ScoutJet'
		, 'Screaming'
		, 'ScreenerBot'
		, 'ScrepyBot'
		, 'Searchestate'
		, 'Seekport'
		, 'SemanticJuice'
		, 'Semrush'
		, 'SentiBot'
		, 'SeoSiteCheckup'
		, 'SeobilityBot'
		, 'Seomoz'
		, 'Shodan'
		, 'Siphon'
		, 'SiteCheckerBotCrawler'
		, 'SiteExplorer'
		, 'SiteLockSpider'
		, 'SiteSnagger'
		, 'SiteSucker'
		, 'Site Sucker'
		, 'Sitebeam'
		, 'Siteimprove'
		, 'Sitevigil'
		, 'SlySearch'
		, 'SmartDownload'
		, 'Snake'
		, 'Snapbot'
		, 'Snoopy'
		, 'SocialRankIOBot'
		, 'Sociscraper'
		, 'Sosospider'
		, 'Sottopop'
		, 'SpaceBison'
		, 'Spammen'
		, 'SpankBot'
		, 'Spanner'
		, 'Spbot'
		, 'SputnikBot'
		, 'Sqlmap'
		, 'Sqlworm'
		, 'Sqworm'
		, 'Steeler'
		, 'Stripper'
		, 'Sucker'
		, 'Sucuri'
		, 'SuperBot'
		, 'SuperHTTP'
		, 'Surfbot'
		, 'SurveyBot'
		, 'Suzuran'
		, 'Swiftbot'
		, 'Szukacz'
		, 'T0PHackTeam'
		, 'T8Abot'
		, 'Teleport'
		, 'TeleportPro'
		, 'Telesoft'
		, 'Telesphoreo'
		, 'Telesphorep'
		, 'TheNomad'
		, 'The Intraformant'
		, 'Thumbor'
		, 'TightTwatBot'
		, 'Titan'
		, 'Toata'
		, 'Toweyabot'
		, 'Tracemyfile'
		, 'Trendiction'
		, 'Trendictionbot'
		, 'True_Robot'
		, 'Turingos'
		, 'Turnitin'
		, 'TurnitinBot'
		, 'TwengaBot'
		, 'Twice'
		, 'Typhoeus'
		, 'URLy.Warning'
		, 'URLy Warning'
		, 'UnisterBot'
		, 'Upflow'
		, 'V-BOT'
		, 'VB Project'
		, 'VCI'
		, 'Vacuum'
		, 'Vagabondo'
		, 'VelenPublicWebCrawler'
		, 'VeriCiteCrawler'
		, 'VidibleScraper'
		, 'Virusdie'
		, 'VoidEYE'
		, 'Voil'
		, 'Voltron'
		, 'WASALive-Bot'
		, 'WBSearchBot'
		, 'WEBDAV'
		, 'WISENutbot'
		, 'WPScan'
		, 'WWW-Collector-E'
		, 'WWW-Mechanize'
		, 'WWW::Mechanize'
		, 'WWWOFFLE'
		, 'Wallpapers'
		, 'Wallpapers/3.0'
		, 'WallpapersHD'
		, 'WeSEE'
		, 'WebAuto'
		, 'WebBandit'
		, 'WebCollage'
		, 'WebCopier'
		, 'WebEnhancer'
		, 'WebFetch'
		, 'WebFuck'
		, 'WebGo IS'
		, 'WebImageCollector'
		, 'WebLeacher'
		, 'WebPix'
		, 'WebReaper'
		, 'WebSauger'
		, 'WebStripper'
		, 'WebSucker'
		, 'WebWhacker'
		, 'WebZIP'
		, 'Web Auto'
		, 'Web Collage'
		, 'Web Enhancer'
		, 'Web Fetch'
		, 'Web Fuck'
		, 'Web Pix'
		, 'Web Sauger'
		, 'Web Sucker'
		, 'Webalta'
		, 'WebmasterWorldForumBot'
		, 'Webshag'
		, 'WebsiteExtractor'
		, 'WebsiteQuester'
		, 'Website Quester'
		, 'Webster'
		, 'Whack'
		, 'Whacker'
		, 'Whatweb'
		, 'Who.is Bot'
		, 'Widow'
		, 'WinHTTrack'
		, 'WiseGuys Robot'
		, 'Wonderbot'
		, 'Woobot'
		, 'Wotbox'
		, 'Wprecon'
		, 'Xaldon WebSpider'
		, 'Xaldon_WebSpider'
		, 'Xenu'
		, 'YoudaoBot'
		, 'Zade'
		, 'Zauba'
		, 'Zermelo'
		, 'Zeus'
		, 'Zitebot'
		, 'ZmEu'
		, 'ZoomBot'
		, 'ZumBot'
		, 'ZyBorg'
		, 'arquivo-web-crawler'
		, 'arquivo.pt'
		, 'autoemailspider'
		, 'backlink-check'
		, 'cah.io.community'
		, 'check1.exe'
		, 'clark-crawler'
		, 'coccocbot'
		, 'cognitiveseo'
		, 'com.plumanalytics'
		, 'crawl.sogou.com'
		, 'crawler.feedback'
		, 'crawler4j'
		, 'dataforseo.com'
		, 'demandbase-bot'
		, 'domainsproject.org'
		, 'eCatch'
		, 'evc-batch'
		, 'facebookscraper'
		, 'gopher'
		, 'instabid'
		, 'internetVista monitor'
		, 'ips-agent'
		, 'isitwp.com'
		, 'iubenda-radar'
		, 'lwp-request'
		, 'lwp-trivial'
		, 'meanpathbot'
		, 'mediawords'
		, 'muhstik-scan'
		, 'oBot'
		, 'page scorer'
		, 'pcBrowser'
		, 'plumanalytics'
		, 'polaris version'
		, 'probe-image-size'
		, 'ripz'
		, 's1z.ru'
		, 'satoristudio.net'
		, 'scan.lol'
		, 'seobility'
		, 'seocompany.store'
		, 'seoscanners'
		, 'seostar'
		, 'sexsearcher'
		, 'sitechecker.pro'
		, 'siteripz'
		, 'sogouspider'
		, 'sp_auditbot'
		, 'spyfu'
		, 'sysscan'
		, 'tAkeOut'
		, 'trendiction.com'
		, 'trendiction.de'
		, 'ubermetrics-technologies.com'
		, 'voyagerx.com'
		, 'webgains-bot'
		, 'webmeup-crawler'
		, 'webpros.com'
		, 'webprosbot'
		, 'x09Mozilla'
		, 'x22Mozilla'
		, 'xpymep1.exe'
		, 'zauba.io'
		, 'zgrab'
		, 'petalsearch'
		, 'protopage'
		, 'Miniflux'
		, 'Feeder'
		, 'Semanticbot' 
		, 'ImageFetcher'
		, 'Mastodon' 
		, 'Neevabot'
		, 'Pleroma'
		, 'Akkoma'
		, 'koyu.space'
		, 'Embedly'
		, 'Mjukisbyxor'
		, 'Giant Rhubarb'
		, 'GozleBot'
		, 'Friendica'
		, 'WhatsApp'
		, 'XenForo'
		, 'Yeti'
		, 'MuckRack'
		, 'PhxBot'
		, 'Bytespider'
		, 'GPTBot'
		, 'SummalyBot'
		, 'LinkedInBot'
		, 'SpiderWeb'
		, 'SpaceCowboys'
		, 'LCC'
		, 'Paqlebot'
		, 'imagesift'
		, 'ows.eu'
		, 'SeznamBot'
		, 'SeznamHomepage'
		, 'ChatGPT'
		, 'Google-Extended'
		, 'GoogleOther'
		, 'anthropic'
		, 'Claude-Web'
		, 'cohere-ai'
		, 'Diffbot'
		, 'FacebookBot'
		, 'ImagesiftBot'
		, 'PerplexityBot'
		, 'Omigili'
		, 'yacybot'
		, 'RepoLookoutBot'
		, 'StractBot'
		, 'IABot'
		, 'rss-is-dead'
		, 'Slackbot'
		, 'Storebot-Google'
		, 'Google-InspectionTool'
		, 'APIs-Google'
		, 'Google-Safety'
		, 'WellKnownBot'
		, 'ArchiveBot'
		, 'Sogou'
		, 'iaskspider'
		, 'Qwantbot'
		, 'keys-so-bot'
		, 'ev-crawler'
		, 'OAI-SearchBot'
		, 'InternetMeasurement'
		, 'meta-externalagent'
		, 'GuzzleHttp'
		, 'AwarioBot'
		, 'NetworkingExtension'
		, 'ApacheBench'
		, 'Adsbot'
		, 'AdsBot-Google'
		, 'AdsBot-Google-Mobile'
		, 'FreshRSS'
		, 'SmartReader'
		, 'http.rb'
		, 'Dazzle BlueSky'
		, 'Bluesky Cardyb'
		, 'TerraCotta'
		, 'IbouBot'
		, 'BUbiNG'
		, 'WPMU DEV'
		, 'sfFeedReader'
		, 'TikTokSpider'
		, 'fedistatsCrawler'
		, 'SkyWatch'
		, 'Instapaper'
		, 'ClaudeBot'
	);
	
	public static function getBotName()
	{
		if (!isset($_SERVER['HTTP_USER_AGENT']))
			return "";
		
		if (!self::$botsSorted)
		{
			usort(self::$bots, fn($a,$b) => strlen($b) <=> strlen($a));
			self::$botsSorted = true;
		}
		
		$userAgent = $_SERVER['HTTP_USER_AGENT'];
		
		foreach (self::$bots as $bot)
		{
			if (stripos($userAgent, $bot) !== false)
				return preg_replace('/[^A-Za-z0-9._-]/', '_', $bot);
		}
	}
	
	public static function isBot()
	{
		if (!isset($_SERVER['HTTP_USER_AGENT']))
			return false;
		
		if ( preg_match('/abacho|accona|AddThis|AdsBot|ahoy|AhrefsBot|AISearchBot|alexa|altavista|anthill|appie|applebot|arale|araneo|AraybOt|ariadne|arks|aspseek|ATN_Worldwide|Atomz|baiduspider|baidu|bbot|bingbot|bing|Bjaaland|BlackWidow|BotLink|bot|boxseabot|bspider|calif|CCBot|ChinaClaw|christcrawler|CMC\/0\.01|combine|confuzzledbot|contaxe|CoolBot|cosmos|crawler|crawlpaper|crawl|curl|cusco|cyberspyder|cydralspider|dataprovider|digger|DIIbot|DotBot|downloadexpress|DragonBot|DuckDuckBot|dwcp|EasouSpider|ebiness|ecollector|elfinbot|esculapio|ESI|esther|eStyle|Ezooms|facebookexternalhit|facebook|facebot|fastcrawler|FatBot|FDSE|FELIX IDE|fetch|fido|find|Firefly|fouineur|Freecrawl|froogle|gammaSpider|gazz|gcreep|geona|Getterrobo-Plus|get|girafabot|golem|googlebot|\-google|grabber|GrabNet|griffon|Gromit|gulliver|gulper|hambot|havIndex|hotwired|htdig|HTTrack|ia_archiver|iajabot|IDBot|Informant|InfoSeek|InfoSpiders|INGRID\/0\.1|inktomi|inspectorwww|Internet Cruiser Robot|irobot|Iron33|JBot|jcrawler|Jeeves|jobo|KDD\-Explorer|KIT\-Fireball|ko_yappo_robot|label\-grabber|larbin|legs|libwww-perl|linkedin|Linkidator|linkwalker|Lockon|logo_gif_crawler|Lycos|m2e|majesticsEO|marvin|mattie|mediafox|mediapartners|MerzScope|MindCrawler|MJ12bot|mod_pagespeed|moget|Motor|msnbot|muncher|muninn|MuscatFerret|MwdSearch|NationalDirectory|naverbot|NEC\-MeshExplorer|NetcraftSurveyAgent|NetScoop|NetSeer|newscan\-online|nil|none|Nutch|ObjectsSearch|Occam|openstat.ru\/Bot|packrat|pageboy|ParaSite|patric|pegasus|perlcrawler|phpdig|piltdownman|Pimptrain|pingdom|pinterest|pjspider|PlumtreeWebAccessor|PortalBSpider|psbot|rambler|Raven|RHCS|RixBot|roadrunner|Robbie|robi|RoboCrawl|robofox|Scooter|Scrubby|Search\-AU|searchprocess|search|SemrushBot|Senrigan|seznambot|Shagseeker|sharp\-info\-agent|sift|SimBot|Site Valet|SiteSucker|skymob|SLCrawler\/2\.0|slurp|snooper|solbot|speedy|spider_monkey|SpiderBot\/1\.0|spiderline|spider|suke|tach_bw|TechBOT|TechnoratiSnoop|templeton|teoma|titin|topiclink|twitterbot|twitter|UdmSearch|Ukonline|UnwindFetchor|URL_Spider_SQL|urlck|urlresolver|Valkyrie libwww\-perl|verticrawl|Victoria|void\-bot|Voyager|VWbot_K|wapspider|WebBandit\/1\.0|webcatcher|WebCopier|WebFindBot|WebLeacher|WebMechanic|WebMoose|webquest|webreaper|webspider|webs|WebWalker|WebZip|wget|whowhere|winona|wlm|WOLP|woriobot|WWWC|XGET|xing|yahoo|YandexBot|YandexMobileBot|yandex|yeti|Zeus|ZoomBot/i', $_SERVER['HTTP_USER_AGENT'])
		)
			{
				return true;
			}

		return false;
	}
}
